#ifndef FS_FSVERSIONVALUES_H
#define FS_FSVERSIONVALUES_H
#pragma message("FS_FSVERSIONVALUES_H")
#define LL_VIEWER_CHANNEL "jira-34020"
#define LL_VIEWER_VERSION_MAJOR 7
#define LL_VIEWER_VERSION_MINOR 1
#define LL_VIEWER_VERSION_PATCH 12
#define LL_VIEWER_VERSION_BUILD 77592
const std::string LL_VIEWER_VERSION_GITHASH {"e8c0b03-0000000"};
#define LLBUILD_CONFIG "Release"
#endif
