#pragma once
#define LL_VIEWER_CHANNEL "FirestormVR-private-gha"
#define LL_VIEWER_VERSION_MAJOR 6
#define LL_VIEWER_VERSION_MINOR 6
#define LL_VIEWER_VERSION_PATCH 17
#define LL_VIEWER_VERSION_BUILD 70368
#define LL_VIEWER_VERSION_GITHASH "FSVRHASH";
#define LLBUILD_CONFIG "Release"
