name: CompileWindows

on:
  # pull_request:
  workflow_dispatch:
      inputs:
        fsbranch:
          type: choice
          description: fstuple
          default: base=6.6.17 repo=FirestormViewer/phoenix-firestorm branch=Firestorm_6.6.17
          options:
            - base=6.6.17 repo=FirestormViewer/phoenix-firestorm branch=Firestorm_6.6.17
            - base=7.1.2 repo=FirestormViewer/phoenix-firestorm-alpha branch=master

defaults:
  run:
    shell: bash

jobs:
  windows_build:
    runs-on: windows-2022
    steps:
    - name: Clone
      shell: bash
      run: |
        pwd && pwd -W
        set -x
        function fastclone() { git clone --quiet --recurse-submodules --filter=tree:0 https://github.com/$1.git --branch $2 $3 ; }
        #fastclone FirestormViewer/phoenix-firestorm ${GITHUB_REF_NAME/_VR/} ${GITHUB_WORKSPACE}
        eval `${{inputs.fstuple}} ; echo _fsbase=$base _fsrepo=$repo _fsbranch=$branch | tee -a $GITHUB_ENV`
        fastclone ${_fsrepo} ${_fsbranch} ${GITHUB_WORKSPACE}
        fastclone FirestormViewer/fs-build-variables master
        fastclone ${GITHUB_REPOSITORY} ${GITHUB_REF_NAME} fsvr
        fastclone ${GITHUB_REPOSITORY} P373R_6.6.8 p373r-vrmod
        ls -lrtha

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true

    #- name: fsvr/detect_vars.sh
    #  run: fsvr/detect_vars.sh Firestorm-VR-GHA `cat build-vc170-64/newview/viewer_version.txt` build-vc170-64 | tee build_vars.env >> $GITHUB_ENV

    - name: Nunja Mapping
      shell: bash
      run: |
        mkdir -pv build-vc170-64
        ./fsvr/util/generate_buid_vars.sh FirestormOS-VR-GHA `cat fsvr/$_fsbase/viewer_version.txt` build-vc170-64/ | tee build_vars.env

    - name: Tools
      shell: bash
      run: |
        curl -L -o ninja-win.zip https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip
        unzip -d humbletim-bin ninja-win.zip
        echo "${GITHUB_WORKSPACE}/humbletim-bin" | tee -a $GITHUB_PATH

    - name: Preflight
      shell: bash
      run: |
        set -x
        bash --version
        python --version
        cmake --version
        ninja --version

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
