name: CompileUbuntu

on: [pull_request]

jobs:
  ubuntu_autobuild:
    runs-on: ubuntu-16.04
    env:
      AUTOBUILD_VSVER: 120
      XZ_DEFAULTS: -T0
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2
    - name: Set env apt
      run: |
        sudo apt-get install -y -qq libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxinerama-dev libxrender-dev gdb
        echo ::set-env name=AUTOBUILD_VARIABLES_FILE::$PWD/fs-build-variables/variables
        echo ::set-env name=LIBRARY_PATH::$PWD/openvr/lib/linux64
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        architecture: x64
    - name: Install autobuild through PIP
      run: pip install git+https://vcs.firestormviewer.org/autobuild-1.1#egg=autobuild
    - name: Get software versions please
      run: |
        cmake --version
        git --version
        python --version
        autobuild --version
        cat /proc/cpuinfo
    - run: df -h
    - name: Configure
      run: |
        autobuild configure -A 64 -c ReleaseFS_open -- --package --openal --chan FirestormVR-GHA -DLL_TESTS:BOOL=FALSE --ninja
    - run: df -h
    - name: Build & Package
      run: |
        autobuild build -A 64 -c ReleaseFS_open -- --package --openal --chan FirestormVR-GHA -DLL_TESTS:BOOL=FALSE --ninja
    - run: df -h
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fs-ubuntu-gha-artifact
        path: build-linux-x86_64/newview/Phoenix*.tar.*
