name: p373r-vrmod

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: string
        required: true
      fstuple:
        type: string
        default: '{"pause":"never"}'

run-name: p373r-vrmod | ${{ inputs.artifact }}

defaults:
  run:
    shell: bash

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: humbletim/firestorm-gha/.github/vrmod@tpv-gha-nunja
      with:
        key: ${{ fromJSON(inputs.fstuple).key }}
        artifact: ${{ inputs.artifact }}

    - name: preflight tests
      run: |
        test -v prefix              || exit 103
        test -v snapshot_dir        || exit 104
        test -s devtime/link.rsp    || exit 100
        test -s devtime/compile.rsp || exit 101
        test -s winsdk/winsdk.rsp   || exit 102
        (
          echo workflow=${{ github.workflow }}
          echo build_id=$(date +"%Y%m%d-%H%M%S")
        ) | tee -a $GITHUB_ENV

    - name: checkout p373r vrmod branch
      shell: bash
      run: |
        repository=humbletim/firestorm-gha
        ref=P373R_6.6.8
        path=p373r
        git clone --quiet --filter=tree:0 --single-branch https://github.com/$repository --branch "$ref" $path 2>&1 \
          | sed -E '/^(remote:|Receive|Resolve)/d'
      # uses: actions/checkout@v4
      # with:
      #   persist-credentials: false
      #   show-progress: false
      #   clean: false
      #   repository: humbletim/firestorm-gha
      #   ref: P373R_6.6.8
      #   path: p373r

    - name: provision p373r vrmod
      run: |
        # . /d/a/_actions/humbletim/firestorm-gha/tpv-gha-nunja/gha/gha.quiet-clone.bash
        # test -d p373r || quiet-clone github.com humbletim/firestorm-gha P373R_6.6.8 p373r
        grep P373R ${snapshot_dir}/source/newview/llviewerdisplay.cpp >/dev/null || \
          ( patch --directory=${snapshot_dir}/source/newview --ignore-whitespace --verbose --merge -p1 < p373r/0001-P373R-6.6.8-baseline-diff.patch )
        cat <<'EOF' | sed 's@^        @@;' | base64 -d | gunzip -c > icon.ico
        H4sICAwo1mcAA2ljb24uaWNvAO1Y+0+TZxT+9h/4035cyJQFLZdSWvrJra2lyApTjNAhRC1YcRlO
        FzMvuylab/MS9Ict2ZYQMl0WtYqXLSpRtkRN3DINIG5uZpkCpf16odAOAgnw7Lynk0SZMfZiTPRp
        TnNy3ue8z3fe2/e2kvQKfVJSJPEtXZ0lSa9KkpRGRiHJKEXjjFnSDOAlYsLU1NRDlixMTk4iEolg
        MDQIf8APxafAq3jh8XrgJfN4B6Z9RVGI4yNukHNEbryYmJhAaCgEv99HuqTnGcDAgJusH4FgAIHB
        ANzkc8zjZo7Pr2CIckRuoiHG+kFd37edxLk2F/silsx5eBTXr12BJU/DJvxnifv3/kblm2aU5Oeg
        JC8HVVYzein2LDA2NobGuloUy2qUGWWUGWSYyW+sr8U4tSUbhz7bBZM2g7Wthqi+8I0UO7Rvd1K1
        O9rPU93ZsBbpSZusSGbjZ6GYGJOO9gtJ0Va8XtjKS7AwXztdc7GsQfF8zX/zMJ/bbGUW4noSru/8
        eDMW6LKi2oaodl5mGptFPAPpCxMc50ebEqp95acO1hP9lxbosCA3E+XmAtQtW4q66kosMhdSLIvb
        BEfMkchJBMbHx7GyqoJqzOY6qxeV4uzJEwjS2Rc9+4HBYBBnT7mwbHEpcwRX5IjceHHadRy6ebNh
        1GXA/nYF+vt6H8t19/XBbqvgvZBLOaddx+LSFrU5am2Q01NhyMlA180bT8zpvPkrDLpMyBlvwFFj
        i+tM7qd6zHIO63+wds10/Iczbfi8eT/7R1q+xm+3uvHjpXZ8900rxwRXzkylXA2PSay41dUJE61n
        ozaddL7imKimYXk1ykx5GAqF0LRlI9avqcdbtAavX7vKnKPEFTkmWqc93Z0x6/9+u4fXfaF6Ho4d
        idZ245ef8f47q3CYzjoR27P9UxzYtR0Hdu+A85MtzDl+tBVFGhXM+mzcoT5ihY/uGaWFMnRzX8f+
        nU0c27tjK75tbcHdP+5gXUMdmj7ciHfrl6Nx1Qq0fPkFcwRX5Cws1FMfSsz6Au857JBVqahdYsU/
        dKcR94/R0VFu671/Dx63G7dp/v+6+yfHIuEwaiqsvGbWOlbGpS1w+eJ5WvvpNJZZPOZPgngHmfVq
        ylHhEuUmAts2b4CR9p9YC817dyI8PDyDE6a6m+ndaCGO4G7dtCEh2tw36a1vsHNN+eq5qCy34OAe
        J864TvBZKHRtFCtQp8GgVWHdavv/PmM8GB0Z4XVlonM+N302tGkpyJ7zGpvw9ao53LbPuQ0jxE0W
        erq7uHZHTRWWlJjIjORX4iDtv3j2+tOCfxfQnEfCwwm557/Ei4mZ/wg8P/gXxoQ5DtoQAAA=
        EOF
        file icon.ico
        set -a
        . ${snapshot_dir}/metadata/env.d/build_vars.env
        CompanyName=${GITHUB_REPOSITORY}
        FileDescription=${GITHUB_WORKFLOW}
        ProductName=$(echo "${GITHUB_WORKFLOW_REF}" | tr '@' '#')
        ProductVersion=${version_full}
        FileVersion=${viewer_version}
        InternalName=${viewer_channel}
        LegalCopyright=$(date +"%Y.%m.%d.%H:%M:%S" )
        icon=icon.ico
        sed -E "$(echo '
                s@\b((FILE|PRODUCT)VERSION\s+(([0-9]+.){3}))[0-9]{5}@\10@g;
                s@(VALUE (.)CompanyName.), .*@    \1, \2${CompanyName}\2    @;
                s@(VALUE (.)ProductName.), .*@    \1, \2${ProductName}\2    @;
                s@(VALUE (.)ProductVersion.), .*@ \1, \2${ProductVersion}\2 @;
                s@(VALUE (.)InternalName.), .*@   \1, \2${InternalName}\2   @;
                s@(VALUE (.)FileDescription.), .*@\1, \2${FileDescription}\2@;
                s@(VALUE (.)FileVersion.), .*@    \1, \2${FileVersion}\2    @;
                s@(VALUE (.)LegalCopyright.), .*@ \1, \2${LegalCopyright}\2 @;
                s@firestorm_icon.ico@${icon}@;
        ' | envsubst)" < ${snapshot_dir}/source/viewerRes.rc > viewerRes.rc

    - name: compile overrides
      run: |
        time bash -c "llvm-rc -c1252 -I${snapshot_dir}/source/newview/res -Iwinsdk/sdk/include/um -Iwinsdk/sdk/include/shared -Fo${snapshot_dir}/objs/newview/viewerRes.rc.res viewerRes.rc && echo rc done" &
        process1_pid=$!
        time bash -c "clang++ @devtime/compile.rsp @winsdk/mm.rsp -Ip373r -includeglh/glh_linear.h $snapshot_dir/source/newview/llviewerdisplay.cpp -c -o $snapshot_dir/objs/newview/llviewerdisplay.cpp.obj && echo compiled" &
        process2_pid=$!
        echo "waiting on subprocesses... $process1_pid $process2_pid"
        wait $process1_pid $process2_pid

    - name: link executable
      run: |
        clang++ @devtime/application-bin.rsp -o ${prefix}-${workflow}.exe

    - name: test executable
      run: |
        test ! -d $snapshot_dir/runtime && echo "skipping (runtime/ not found)" || \
        PATH=$PATH:$snapshot_dir/runtime EXEROOT=$snapshot_dir/runtime timeout 3 ./${prefix}-p373r-vrmod.exe --help 2>&1 | tail -5 || true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        retention-days: 1
        name: ${{ env.build_id }}-${{ env.prefix }}-${{ env.workflow }}
        path: ${{ env.prefix }}-${{ env.workflow }}.exe

    - name: gha_step recovery
      if: (failure() && fromJSON(inputs.fstuple).pause != 'never') || fromJSON(inputs.fstuple).pause == 'always'
      run: |
        cat <<'EOF' > _yaml.bash
          ghash=/d/a/_actions/humbletim/firestorm-gha/tpv-gha-nunja/gha
          . $ghash/gha.quiet-clone.bash
          test -d clone || quiet-clone github.com humbletim/firestorm-gha tpv-gha-nunja clone
          test -x bin/yaml2json || (
            . $ghash/gha.wget-sha256.bash
            . $ghash/../gha-populate-bin.bash
              mkdir -pv bin
              get_yaml2json-windows
          )
          . $ghash/../gha-steps.bash
          workflow=clone/.github/workflows/p373r-vrmod.yml
        EOF


    - name: ~Setup tmate session
      if: (failure() && fromJSON(inputs.fstuple).pause != 'never') || fromJSON(inputs.fstuple).pause == 'always'
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
