name: ReleaseFS_open

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true

run-name: ReleaseFS_open | ${{ inputs.ref }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Viewer
        uses: actions/checkout@v5
        with:
          repository: FirestormViewer/phoenix-firestorm
          ref: ${{ inputs.ref }}
          fetch-depth: 0         # request "all" commits...
          filter: tree:0         # ...BUT don't download trees or file blobs for them!
          path: .

      - name: Checkout tpv-gha-nunja
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          repository: humbletim/firestorm-gha
          ref: tpv-gha-nunja
          path: tpv-gha-nunja

      - name: Checkout p373r-vrmod
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          repository: humbletim/p373r-vrmod
          ref: main
          path: p373r-vrmod-main

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install autobuild dependencies
        run: pip install -r requirements.txt

      - name: Set up build variables
        run: |
          git clone https://github.com/FirestormViewer/fs-build-variables.git build-variables
          echo "AUTOBUILD_VARIABLES_FILE=$PWD/build-variables/variables" >> $GITHUB_ENV
          echo "AUTOBUILD_VSVER=170" >> $GITHUB_ENV

      - name: Provision 3p-openvr
        run: |
          set -Euo pipefail
          source p373r-vrmod-main/misc/3p-openvr/improvise.bash
          provision_openvr $PWD
          autobuild installables add --archive file:///`cygpath -m $PWD/openvr-v*.*.*.*.tar.bz2`
          autobuild install openvr --verbose

      - name: Provision 3p-p373r-vrmod
        run: |
          set -Euo pipefail
          source p373r-vrmod-main/misc/3p-p373r-vrmod/improvise.bash
          provision_p373r_vrmod $PWD
          autobuild installables add --archive file:///`cygpath -m $PWD/p373r-vrmod-v*.*.*.*.tar.bz2`
          autobuild install p373r-vrmod --verbose

      - name: Install NSIS
        run: choco install nsis

      - name: Configure (open source build)
        run: |
          autobuild configure -A 64 -c ReleaseFS_open -- --package -DLL_TESTS:BOOL=FALSE

      - name: ~Setup tmate session
        if: always()
        # if: (failure() && inputs.pause != 'never') || inputs.pause == 'always'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Build
        run: |
          autobuild build -A 64 -c ReleaseFS_open --no-configure

      - name: Upload unsigned installer
        uses: actions/upload-artifact@v4
        with:
          name: firestorm-installer
          path: build-*/newview/Release/*Setup.exe

      - name: ~Setup tmate session
        if: always()
        # if: (failure() && inputs.pause != 'never') || inputs.pause == 'always'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

