name: ReleaseFS_open

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true

run-name: ReleaseFS_open | ${{ inputs.ref }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repos
        run: |
          set -xEuo pipefail

          # 1. Checkout Viewer (treeless clone, full history)
          git clone --branch ${{ inputs.ref }} --filter=tree:0 --no-progress https://github.com/FirestormViewer/phoenix-firestorm.git . &

          # 2. Checkout tpv-gha-nunja (shallow clone)
          git clone --depth 1 --branch tpv-gha-nunja --single-branch --no-progress https://github.com/humbletim/firestorm-gha.git ../tpv-gha-nunja &

          # 3. Checkout p373r-vrmod (shallow clone)
          git clone --depth 1 --branch main --single-branch --no-progress https://github.com/humbletim/p373r-vrmod.git ../p373r-vrmod-main &

          # 4. Checkout fs-build-variables (shallow clone)
          git clone --depth 1 --branch master --single-branch --no-progress https://github.com/FirestormViewer/fs-build-variables.git ../build-variables &

          _pythonx64=`ls -1d /c/hostedtoolcache/windows/Python/3.*/x64/ | sort -h | tail -1`
          (
            echo "$_pythonx64/Scripts"
            echo "$_pythonx64"
          ) | tee -a $GITHUB_PATH

          export PATH="$PATH:$_pythonx64/Scripts:$_pythonx64"
          echo "AUTOBUILD_VARIABLES_FILE=$PWD/../build-variables/variables" >> $GITHUB_ENV
          echo "AUTOBUILD_VSVER=170" >> $GITHUB_ENV

          wait
          ln -s ../tpv-gha-nunja/gha-node20-run
          pip install -r requirements.txt
          choco install nsis --no-progress &

      - name: Preflight Check
        uses: ./gha-node20-run
        with:
          run: echo OK

      - name: Provision 3p-openvr_api
        run: |
          set -Euo pipefail
          source ../p373r-vrmod-main/misc/3p-openvr_api/improvise.bash
          provision_openvr_api $PWD
          autobuild installables add --archive file:///`cygpath -m $PWD/openvr_api-v*.*.*.*.tar.bz2`
          autobuild install openvr_api --verbose

      - name: Precompile Devtime
        run: |
          autobuild configure -A 64 -c ReleaseFS_open -- --avx2 --package -DLL_TESTS:BOOL=FALSE
          cmake --source viewer --build build-vc170-64 --target firestorm-bin --config Release

      - name: Snapshot Devtime
        uses: ./gha-node20-run
        with:
          run: |
            set -Euo pipefail
            export ghash=$PWD/../tpv-gha-nunja/gha
            source ../tpv-gha-nunja/.github/workflows/ReleaseFS_open.yml.bash
            generate_env && generate_devtime

      - name: Provision 3p-p373r-vrmod
        run: |
          set -Euo pipefail
          source ../p373r-vrmod-main/misc/3p-p373r-vrmod/improvise.bash
          provision_p373r_vrmod $PWD
          autobuild installables add --archive file:///`cygpath -m $PWD/p373r-vrmod-v*.*.*.*.tar.bz2`
          autobuild install p373r-vrmod --verbose
          PATH=/c/Program\ Files/Git/usr/bin:$PATH patch --directory=indra/newview --ignore-whitespace --verbose --merge -p1 < ../p373r-vrmod-main/sgeo-minimal/0001-sgeo_min_vr_7.1.9-baseline-diff.patch
          git diff || true

      - name: Compile VR Mod
        run: |
          cmake --build build-vc170-64 --target firestorm-bin --config Release

      - name: Generate VR Mod Installer Setup.exe
        run: |
          # autobuild build -A 64 -c ReleaseFS_open --no-configure
          cmake --build build-vc170-64 --target llpackage --config Release

      - name: Upload Community VR Mod Installer
        uses: ./gha-node20-run
        with:
          run: |
            source tpv-gha-nunja/gha/gha.upload-artifact.bash
            gha-upload-artifact-fast community-vrmod-firestorm build-*/newview/Release/*Setup.exe 7

      # - name: Upload VR Mod Setup.exe
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: community-vrmod-firestorm
      #     path: build-*/newview/Release/*Setup.exe

      - name: ~Setup tmate session
        if: always()
        # if: (failure() && inputs.pause != 'never') || inputs.pause == 'always'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

